# Generated by Django 3.0.8 on 2020-07-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('decription', models.TextField(default=None)),
                ('button_title', models.CharField(max_length=30)),
                ('button_link', models.URLField()),
            ],
        ),
    ]
